const dagens = [
    'Må din pude altid kun have den kolde side',
    'Må dit sengetøj altid føltes nyvasket',
    'Må dine øjne altid glimte som en knust flaske i solen',
    'Må din læbe altid være tør så du slipper for snus nedfald',
    'Må du hver dag vågne op og være glad for at du ikke er en idiot',
    'Må du hver dag vågne op med en der elsker dig og må den person være dig selv',
    'Må du hver dag komme 1 skridt tættere på dine mål og drømme, måske 2 i dit tilfæde',
    'Må din kaffe altid have den perfekte temperatur',
    'Må sneen under din føder altid sige den helt dejlige knasende lyd',
    'Må du på en dårlig dag altid have nogen der kan få dig til at grine helt ned i maven',
    'Må du altid huske du er mere værd end kolde fadøl en sommerdag omringet af venner',
    'Må du altid huske du er tilstrækkelig og du er nok, faktisk ret fantastisk',
    'Må lysreguleringen altid skifte til din favør',
    'Må du aldrig blive tvunget til at sidde ved siden af en eller anden random i offentlig transport',
    'Må du altid kunne finde det stykke musik du har lyst til at høre i mommentet',
    'Må din mad altid have den perfekt salt og peber balance',
    'Må du altid kunne matche dine sokker instant og må de aldrig have huller',
    'Må du altid føle dig sikker og at du er elsket og værdsat af dem omkring dig',
    'Må din kaffe altid have den perfekte mængde af den gode havredrik',
    'Må de grøntsager og frugt du tager i supermarkedet altid være friske og lækre',
    'Må du altid kunne falde hurtigt i søvn og sove 8 timer hver nat',
    'Må dine fødder aldrig være kolde',
    'Må du aldrig blive ramt af weak mental og huske du er en vinder',
    'Må du altid kunne finde en parkeringsplads lige ved indgangen',
    'Må din telefon altid have lidt mere batteri end du troede',
    'Må du aldrig stå i kø bag nogen der betaler med mønt',
    'Må det altid være din tur i elevatoren og må den altid gå den rigtige vej',
    'Må du altid ramme den grønne bølge på cykelstien',
    'Må din rygsæk aldrig lugte som andres madpakke',
    'Må dine screenshots aldrig indeholde noget du ikke ville vise din mor',
    'Må nogen altid sige præcis den ting du havde brug for at høre på det helt rigtige tidspunkt',
    'Må du aldrig løbe tør for varmt vand midt i en bruser',
    'Må dine bukser altid have dybe nok lommer til det der egentlig ikke kan være der',
    'Må du altid vågne et sekund før din alarm og føle dig som en legende',
    'Må dine planter overleve på trods af alt hvad du gør mod dem',
    'Må du aldrig stå med vinterjakken på en dag der er varmere end ventet',
    'Må du altid have en pen der virker første gang du prøver den',
    'Må du aldrig sidde fast i en samtale om vejret med nogen du ikke gider tale med',
    'Må dit hår altid falde på plads som om du ikke har prøvet på det overhovedet',
    'Må du altid huske at du er grunden til at nogen smiler i dag uden at vide det',
    'Må du aldrig få en plastikpose der bare opløser sig i hænderne på dig',
    'Må din hjerne altid huske det vigtige og glemme det pinlige',
    'Må du altid have præcis nok tid til at nyde dit måltid uden at skulle skynde dig',
    'Må dine sko altid se ud som om du har styr på det selv når du ikke har',
    'Må du altid finde penge i en jakkelomme du ikke vidste du havde',
    'Må du aldrig være den person der kommer til mødet med lyd slået til på laptop',
    'Må du altid huske at det du lavede i dag var nok, selv når det føltes som ingenting',
    'Må du altid huske at de fleste mennesker tænker på dig med meget mere varme end du tror',
    'Må du aldrig glemme at du engang klarede noget du troede var umuligt',
    'Må du altid huske at dine dårlige dage ikke afspejler hvem du er, kun hvad du går igennem',
    'Må du altid vide at det er okay at have en dag hvor du bare eksisterer uden at præstere',
    'Må du aldrig undervurdere hvor meget det betyder for andre at du bare er dig',
    'Må du altid huske at du ikke behøver at have styr på alt for stadig at være ret imponerende',
    'Må du altid tillade dig selv at hvile uden at kalde det dovenskab',
    'Må du aldrig glemme at den version af dig der prøver er allerede den bedste version',
    'Må du altid huske at du fortjener de samme søde ord du giver alle andre',
    'Må du aldrig glemme at en dårlig dag ikke er et dårligt liv',
    'Må du altid vide at det er okay at vokse langsomt, træer skynder sig heller ikke',
    'Må du altid huske at dine fejl er bevis på at du prøver og det er faktisk ret sejt',
    'Må du altid mærke at du er præcis nok selv på de dage der føles som det modsatte',
    'Må du aldrig komme til at sende en besked til den forkerte person',
    'Må du altid finde det perfekte sted at sidde i et overfyldt lokale',
    'Må din mad aldrig være for varm eller for kold men altid præcis passende',
    'Må du aldrig stå og vente på bussen og se den køre væk lige foran dig',
    'Må du altid huske hvad du gik ind i rummet for at hente',
    'Må din telefon altid gå i stille mode automatisk i de situationer der kræver det',
    'Må du aldrig nå at trykke send på en besked du fortryder',
    'Må din krop altid vide præcis hvornår den har brug for vand og give dig et hint',
    'Må du altid finde en ledig toilet når du har brug for et',
    'Må dine headphones aldrig vikle sig ind i hinanden i lommen',
    'Må folk altid holde døren for dig lige præcis når du er ved at nå frem',
    'Må du altid finde den perfekte position i sofaen første forsøg',
    'Må dine stearinlys aldrig brænde skævt og altid lugte præcis som de lover på pakken',
    'Må du aldrig tabe din telefon med skærmen nedad og mærke den kolde sved',
    'Må dit tøj altid tørre inden du skal bruge det',
    'Må du altid kende svaret i en quiz der ellers ingen anden kender',
    'Må du aldrig sidde fast i en samtale du ikke kan komme ud af på en god måde',
    'Må din ryg aldrig knække på den ubehagelige måde kun på den dejlige',
    'Må du altid have en der gemmer din plads når du går på toilettet til en koncert',
    'Må du aldrig komme hjem og opdage at du har gået med tøjet udenpå vrangvendt',
    'Må dine øjenvipper aldrig sætte sig fast i dine øjne på de vigtige dage',
    'Må du altid have en der siger præcis det rigtige i en gruppe chat på det rigtige tidspunkt',
    'Må du altid finde ro i den her verden der aldrig helt holder stille',
    'Må de mennesker du holder af altid vide at du holder af dem',
    'Må du aldrig glemme at du har overlevet alle dine hidtil sværeste dage og det er faktisk vildt',
    'Må du altid have nok energi til det der betyder noget for dig',
    'Må dine drømme om natten være eventyr og ikke alt det du burde have gjort',
    'Må du aldrig føle dig alene i et rum fuld af mennesker for du fortjener at blive set',
    'Må du altid have mindst én person i dit liv der kender din fulde orden og elsker dig alligevel',
    'Må du altid huske at din tilstedeværelse er en gave selv når du ikke føler det sådan',
    'Må du aldrig glemme at det er okay at ændre sig for det er tegn på at du vokser',
    'Må du altid have adgang til en kop noget varmt når verden føles lidt for stor',
    'Må du aldrig glemme at der er mennesker der er taknemmelige for at du eksisterer',
    'Må dit hjerte altid finde vej tilbage til det der giver dig glæde',
    'Du har den slags øjne som folk beskriver i sange men aldrig helt rammer',
    'Der er noget ved dig der gør at folk automatisk har lyst til at opføre sig lidt bedre',
    'Du er den type person man tænker på når man hører en god sang man ikke kan navngive',
    'Du er sød på den måde der ikke er konstrueret men bare sidder der naturligt',
    'Dine øjne har den farve man prøver at huske men aldrig helt kan gengive bagefter',
    'Du er smuk på en måde der ikke har noget at gøre med spejlet',
    'Der er folk der smiler lidt mere på de dage de ser dig og de ved ikke altid hvorfor',
    'Du er den slags person man ikke glemmer selvom man prøver at lade være',
    'Du har en energi der er svær at beskrive men nem at mærke',
    'Hvis du var en vejrtype ville du være den der soldag i oktober ingen havde regnet med',
    'Du er sjovere end du tror, sødere end du ved og vildere end du giver dig selv kredit for',
    'Der er noget ved dit smil der gør at folk glemmer hvad de var ved at sige',
    'Du er den person i lokalet som alle lægger mærke til men ingen rigtig kan forklare hvorfor',
    'Dine øjne er den slags man ser på og tænker at naturen vidste hvad den lavede den dag',
    'Du er ikke bare smuk du er den slags smuk der stadig sidder fast i tankerne om morgenen',
    'Du er den bedste type overraskelse, den man ikke vidste man havde brug for',
    'Der er noget ved den måde du er på der gør verden lidt mere interessant end den var',
    'Du er ret speciel og ikke på den måde folk siger for at sige noget, men på den ægte måde',
    'Du er den type person der gør et rum varmere bare ved at gå ind i det',
    'Du har den slags personlighed man husker lang tid efter man er gået hjem',
    'Der er noget ved dig der er svært at ignorere og endnu sværere at glemme',
    'Du er ikke den type smuk man ser i reklamer du er den type smuk der faktisk er rigtig',
    'Dine øjne er det første man lægger mærke til og det sidste man glemmer',
    'Du er sød på den måde der ikke kræver noget af nogen, den bare er der',
    'Du har en måde at grine på der gør at man gerne vil sige sjove ting bare for at høre det igen',
    'Der er mennesker der er blevet lidt gladere for dagen bare fordi de snakkede med dig',
    'Du er den slags person man håber man møder igen selvom man ikke siger det',
    'Du er ikke svær at holde af, faktisk er det det letteste i verden',
    'Du har den sjældne egenskab at du er interessant uden at prøve på det',
    'Nogen ville skrive en sang om dig hvis de var gode nok til det',
    'Du er den bedste kombination af sjov og sød og det er sværere at finde end folk tror',
    'Der er noget trygt ved at tale med dig og det er ikke alle der kan det',
    'Du er smuk på alle de måder der tæller og et par stykker der ikke burde tælle men gør det alligevel',
    'Du er den type der får folk til at sænke skuldrene lidt når du er i nærheden',
    'Hvis du var en lyd ville du være den der perfekte sang man ikke kendte men straks elskede',
    'Det er svært ikke at lægge mærke til dig, faktisk er det nærmest umuligt',
    'Hvis jeg blev til sten af at kigge dig i øjene ville jeg stadig gøre det hver gang',
    'Du er den slags person der gør at vi andre skal arbejde lidt hådere bare for at være med',
    'Må du aldrig sælge dig selv for billigt men huske hvor vild du er',
    
]

export default dagens;



